default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: flauteando_dev
  username: flauteando_dev
  password: flauteando_dev

test:
  <<: *default
  database: flauteando_test
  username: flauteando_test
  password: flauteando_test
